/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DevPublishPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/image-mapping-dialog.ts
var import_obsidian = require("obsidian");
var createTable = (element, list) => {
  const table = element.createEl("table", { attr: { style: "width: 100%" } });
  const inputs = {};
  const thead = table.createEl("thead");
  {
    const tr = thead.createEl("tr");
    tr.createEl("th", { text: "Image" });
    tr.createEl("th", { text: "Public URL" });
  }
  const tbody = table.createEl("tbody");
  for (const item of list) {
    const tr = tbody.createEl("tr");
    tr.createEl("td", { text: item.imageFile });
    const input = tr.createEl("td").createEl("input", {
      value: item.publicUrl,
      type: "text",
      attr: {
        style: "width: 100%",
        "aria-label": `Enter the public URL where the embedded image "${item.imageFile}" can be found`
      }
    });
    inputs[item.imageFile] = input;
  }
  return { table, inputs };
};
var showDialog = (app, list) => {
  return new Promise((resolve) => {
    let submitting = false;
    const dialog = new import_obsidian.Modal(app);
    dialog.onClose = function() {
      if (!submitting) {
        resolve(null);
      }
    };
    dialog.setTitle("Map image links");
    dialog.contentEl.createEl("p", {
      text: "Image embeds cannot be uploaded to DEV automatically. You need to make them available, e.g. by uploading manually on DEV, or through some other service. Once done, you can provide the mapping here."
    });
    const form = dialog.contentEl.createEl("form");
    const { inputs } = createTable(form, list);
    form.createEl("button", { type: "submit", text: "Submit" });
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      submitting = true;
      dialog.close();
      resolve(
        list.map((x) => ({
          imageFile: x.imageFile,
          publicUrl: inputs[x.imageFile].value
        }))
      );
    });
    dialog.open();
  });
};
var TheDialogController = class {
  constructor(app) {
    this.app = app;
  }
  showImageMappingDialog(list) {
    return showDialog(this.app, list);
  }
};

// src/validation.ts
var isNumber = (x) => typeof x === "number";
var isString = (x) => typeof x === "string";
var isObjectType = (x) => typeof x === "object" && x !== null;
var isObject = (input, spec) => {
  if (!isObjectType(input)) {
    return false;
  }
  for (const key of Object.keys(spec)) {
    if (!(key in input)) {
      return false;
    }
    const actual = input[key];
    const validator = spec[key];
    if (!validator(actual)) {
      return false;
    }
  }
  return true;
};
var isArray = (input, spec) => Array.isArray(input) && input.every((x) => spec(x));

// src/medium-gateway.ts
var bodyFromArticle = ({ markdown, ...rest }) => ({
  article: {
    body_markdown: markdown,
    ...rest
  }
});
var postArticle = async (input, requestUrl2) => {
  const body = bodyFromArticle(input.article);
  const response = await requestUrl2({
    url: "https://dev.to/api/articles",
    method: "POST",
    body: JSON.stringify(body),
    headers: {
      "api-key": input.apiKey
    },
    contentType: "application/json"
  });
  return response.json;
};
var putArticle = async (input, requestUrl2) => {
  const { articleId, article, apiKey } = input;
  const body = bodyFromArticle(article);
  console.log("Update dev article", { articleId, body });
  await requestUrl2({
    url: `https://dev.to/api/articles/${articleId}`,
    method: "PUT",
    body: JSON.stringify(body),
    headers: {
      "api-key": apiKey
    },
    contentType: "application/json"
  });
};
var verifyArticle = (data) => {
  return isObject(data, {
    id: isNumber,
    url: isString,
    canonical_url: isString
  });
};
var MediumGateway = class {
  constructor(apiKey, requestUrl2) {
    this.apiKey = apiKey;
    this.requestUrl = requestUrl2;
  }
  async createArticle(input) {
    const temp = await postArticle(
      { apiKey: this.apiKey, article: input.article },
      this.requestUrl
    );
    if (!verifyArticle(temp)) {
      throw new Error("Bad response");
    }
    const { id, url, canonical_url } = temp;
    return { id, url, canonicalUrl: canonical_url };
  }
  async updateArticle(input) {
    return await putArticle(
      { apiKey: this.apiKey, article: input.article, articleId: input.id },
      this.requestUrl
    );
  }
  async getArticleStatus(input) {
    const params = {
      url: `https://dev.to/api/articles/${input.id}`,
      throw: false
    };
    const response = await this.requestUrl(params);
    switch (response.status) {
      case 404:
        return { published: false };
      case 200: {
        const data = await response.json;
        if (!(data && typeof data === "object" && "published_at" in data)) {
          throw new Error(
            "Unexpected response from DEV. Please file an issue, and attach the console logs (check if they contain any sensitive information data first)"
          );
        }
        if (!verifyArticle(data)) {
          throw new Error("Bad data retrieved from server");
        }
        return {
          published: true,
          url: data.url,
          canonicalUrl: data.canonical_url
        };
      }
      default:
        throw new Error("Unexpected status");
    }
  }
};

// src/obsidian-implementations.ts
var import_obsidian2 = require("obsidian");
var GetFrontMatterInfo = class {
  getFrontMatterInfo(contents) {
    return (0, import_obsidian2.getFrontMatterInfo)(contents);
  }
};

// src/publisher.ts
var ARTICLE_ID_KEY = "dev-article-id";
var ARTICLE_URL_KEY = "dev-url";
var ARTICLE_CANONICAL_URL_KEY = "dev-canonical-url";
var ARTICLE_IMAGE_MAP_KEY = "dev-image-map";
var ARTICLE_PUBLISHED = "dev-published";
var IMAGE_EXTENSIONS = [".png", ".jpg", ".jpeg", ".gif", ".webp", ".heif"];
var replaceInstructionsEqual = (a, b) => a.from === b.from && a.to === b.to && a.replaceString === b.replaceString;
var isImageMap = (input) => isObject(input, {
  publicUrl: isString,
  imageFile: isString
});
var isMapping = (input) => isArray(input, isImageMap);
var removeDuplicateReplaceInstructions = (instructions) => {
  return instructions.filter(
    (value, index) => index === instructions.findIndex(
      (search) => replaceInstructionsEqual(value, search)
    )
  );
};
var processInlineMathJax = (jax) => {
  const matches = [...jax.matchAll(/(\${1})([^\n$]+)\1/g)];
  return matches.map((match) => {
    const matchJax = match[2];
    if (typeof match.index !== "number") {
      return void 0;
    }
    return {
      from: match.index,
      to: match.index + match[0].length,
      replaceString: `{% katex inline %}
 ${matchJax}
{% endkatex %}`
    };
  }).filter((x) => typeof x !== "undefined");
};
var processBlockMathJax = (jax) => {
  const matches = [...jax.matchAll(/(\${2})([^$]+)\1/g)];
  return matches.map((match) => {
    const matchJax = match[2];
    if (typeof match.index !== "number") {
      return void 0;
    }
    return {
      from: match.index,
      to: match.index + match[0].length,
      replaceString: `{% katex %}
${matchJax.trim()}
{% endkatex %}`
    };
  }).filter((x) => typeof x !== "undefined");
};
var Publisher = class {
  constructor(app, gateway, getFrontMatterInfo2) {
    this.app = app;
    this.fileManager = app.fileManager;
    this.gateway = gateway;
    this.vault = app.vault;
    this.getFrontMatterInfo = getFrontMatterInfo2;
  }
  getFrontMatter(file) {
    var _a;
    return (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
  }
  applyReplaceInstruction(replaceInstructions, contents) {
    const flattened = replaceInstructions.filter(
      (x) => !replaceInstructions.find((y) => x.from > y.from && x.to < y.to)
    );
    flattened.sort((a, b) => a.from - b.from);
    const result = flattened.reduce(
      (prev, curr) => {
        const toKeep = contents.substring(prev.lastIndex, curr.from);
        return {
          result: [...prev.result, toKeep, curr.replaceString],
          lastIndex: curr.to
        };
      },
      { result: [], lastIndex: 0 }
    );
    const finalResult = [
      ...result.result,
      contents.substring(result.lastIndex)
    ].join("");
    return finalResult;
  }
  async processLinks(file, cachedMetadata) {
    const links = cachedMetadata == null ? void 0 : cachedMetadata.links;
    if (!links) {
      return [];
    }
    const replaceInstructions = links.map((link) => {
      const targetFile = this.app.metadataCache.getFirstLinkpathDest(
        link.link,
        file.path
      );
      const frontmatter = targetFile && this.getFrontMatter(targetFile);
      const url = frontmatter == null ? void 0 : frontmatter.url;
      const displayText = link.displayText || link.link;
      const replaceString = url ? `[${displayText}](${url})` : displayText;
      return [
        {
          from: link.position.start.offset,
          to: link.position.end.offset,
          replaceString
        }
      ];
    }).flat();
    return removeDuplicateReplaceInstructions(replaceInstructions);
  }
  processImages(_file, md) {
    if (!(md == null ? void 0 : md.embeds)) {
      return [];
    }
    const frontmatter = md.frontmatter;
    const imageMap = frontmatter && frontmatter[ARTICLE_IMAGE_MAP_KEY];
    const getExistingMap = (file) => {
      var _a;
      return isMapping(imageMap) && ((_a = imageMap.find((x) => x.imageFile === `[[${file}]]`)) == null ? void 0 : _a.publicUrl);
    };
    return md.embeds.flatMap((embed) => {
      const publicUrl = getExistingMap(embed.link);
      const displayText = embed.displayText || embed.link;
      const { start, end } = embed.position;
      return publicUrl ? [
        {
          replaceString: `![${displayText}](${publicUrl})`,
          from: start.offset,
          to: end.offset
        }
      ] : [];
    });
  }
  async generateMarkdown(file) {
    var _a;
    const originalContents = await this.vault.read(file);
    const metadataCache = this.app.metadataCache.getFileCache(file);
    const frontmatter = (metadataCache == null ? void 0 : metadataCache.frontmatter) || {};
    const markdownLinkReplaceInstructions = await this.processLinks(
      file,
      metadataCache
    );
    const imageEmbedsReplaceInstructions = this.processImages(
      file,
      metadataCache
    );
    const h1 = (_a = metadataCache == null ? void 0 : metadataCache.headings) == null ? void 0 : _a.find((x) => x.level === 1);
    const h1Instructions = h1 ? [
      {
        from: 0,
        to: h1.position.end.offset,
        replaceString: ""
      }
    ] : [];
    if (frontmatter["dev-enable-mathjax"]) {
      markdownLinkReplaceInstructions.splice(
        markdownLinkReplaceInstructions.length,
        0,
        ...processInlineMathJax(originalContents)
      );
      markdownLinkReplaceInstructions.splice(
        markdownLinkReplaceInstructions.length,
        0,
        ...processBlockMathJax(originalContents)
      );
    }
    const dataAfterHeading = this.applyReplaceInstruction(
      [
        h1Instructions,
        markdownLinkReplaceInstructions,
        imageEmbedsReplaceInstructions
      ].flat(),
      originalContents
    );
    const frontmatterInfo = this.getFrontMatterInfo.getFrontMatterInfo(dataAfterHeading);
    const markdown = (frontmatterInfo.exists ? dataAfterHeading.substring(frontmatterInfo.contentStart) : dataAfterHeading).trim();
    return markdown;
  }
  generateTitle(file) {
    var _a;
    const metadataCache = this.app.metadataCache.getFileCache(file);
    const h1 = (_a = metadataCache == null ? void 0 : metadataCache.headings) == null ? void 0 : _a.find((x) => x.level === 1);
    return (h1 == null ? void 0 : h1.heading) || "Heading Missing";
  }
  async getArticleData(file) {
    var _a, _b;
    const parseTags = (tags2) => {
      if (!Array.isArray(tags2)) {
        return void 0;
      }
      return tags2.filter((x) => typeof x === "string").slice(0, 4);
    };
    const parseString = (value) => {
      if (typeof value === "string") {
        return value;
      }
      return void 0;
    };
    const metadataCache = this.app.metadataCache.getFileCache(file);
    const markdown = await this.generateMarkdown(file);
    const title = this.generateTitle(file);
    const tags = parseTags((_a = metadataCache == null ? void 0 : metadataCache.frontmatter) == null ? void 0 : _a["dev-tags"]);
    const series = parseString((_b = metadataCache == null ? void 0 : metadataCache.frontmatter) == null ? void 0 : _b["dev-series"]);
    return {
      title,
      markdown,
      tags,
      series
    };
  }
  async updateFrontmatter(file, newData) {
    await this.fileManager.processFrontMatter(file, (existing) => {
      for (const key of Object.keys(newData)) {
        existing[key] = newData[key];
      }
    });
  }
  async publish(file) {
    const frontmatter = this.getFrontMatter(file);
    const mediumId = frontmatter && frontmatter[ARTICLE_ID_KEY];
    const article = await this.getArticleData(file);
    if (typeof mediumId === "number") {
      await this.updateStatus(file);
      await this.gateway.updateArticle({ id: mediumId, article });
    } else {
      const result = await this.gateway.createArticle({ article });
      const newFrontmatter = {
        [ARTICLE_ID_KEY]: result.id,
        [ARTICLE_URL_KEY]: result.url,
        [ARTICLE_CANONICAL_URL_KEY]: result.canonicalUrl
      };
      this.updateFrontmatter(file, newFrontmatter);
    }
  }
  async updateStatus(file) {
    const frontmatter = this.getFrontMatter(file);
    const id = frontmatter && frontmatter[ARTICLE_ID_KEY];
    if (typeof id === "number") {
      const status = await this.gateway.getArticleStatus({ id });
      await this.fileManager.processFrontMatter(file, (fm) => {
        fm[ARTICLE_PUBLISHED] = status.published;
        if (status.published) {
          fm[ARTICLE_URL_KEY] = status.url;
          fm[ARTICLE_CANONICAL_URL_KEY] = status.canonicalUrl;
        }
      });
    }
  }
  async mapImages(file, dialogController) {
    var _a, _b;
    const md = this.app.metadataCache.getFileCache(file);
    if (!md) {
      return;
    }
    const frontmatter = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const imageMap = frontmatter && frontmatter[ARTICLE_IMAGE_MAP_KEY];
    const getExistingMap = (file2) => {
      var _a2;
      return isMapping(imageMap) && ((_a2 = imageMap.find((x) => x.imageFile === `[[${file2}]]`)) == null ? void 0 : _a2.publicUrl);
    };
    const getExtension = (link) => {
      const index = link.lastIndexOf(".");
      return index === -1 ? "" : link.substring(index);
    };
    const list = ((_b = md.embeds) == null ? void 0 : _b.map((x) => ({
      imageFile: x.link,
      publicUrl: getExistingMap(x.link) || ""
    })).filter(
      ({ imageFile }) => IMAGE_EXTENSIONS.includes(getExtension(imageFile))
    )) || [];
    const result = await dialogController.showImageMappingDialog(list);
    if (result) {
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm[ARTICLE_IMAGE_MAP_KEY] = result && result.map((x) => ({ ...x, imageFile: `[[${x.imageFile}]]` })).filter((x) => x.publicUrl);
      });
    }
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  apiKey: ""
};
var DevPublishPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "map-image-files",
      name: "Map embedded images to public URLs",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (view && view.file) {
          if (!checking) {
            const publisher = new Publisher(
              this.app,
              new MediumGateway(this.settings.apiKey, import_obsidian3.requestUrl),
              new GetFrontMatterInfo()
            );
            publisher.mapImages(view.file, new TheDialogController(this.app));
          }
          return true;
        }
      }
    });
    this.addCommand({
      id: "publish-current-note",
      name: "Create/update article",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (view && view.file) {
          if (!checking) {
            const publisher = new Publisher(
              this.app,
              new MediumGateway(this.settings.apiKey, import_obsidian3.requestUrl),
              new GetFrontMatterInfo()
            );
            publisher.publish(view.file).then(
              () => {
                console.log("Article published to dev.to");
              },
              (err) => {
                console.error("Error publishing to dev.to", err);
                new import_obsidian3.Notice(
                  "Publish to DEV: Creating/updating DEV article failed. \nPlease check your access token, and try again.\nIf you wish to file a bug report, please see the project readme page.",
                  0
                );
              }
            );
          }
          return true;
        }
      }
    });
    this.addSettingTab(new DevPublishSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var DevPublishSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("API key").setDesc(
      (0, import_obsidian3.sanitizeHTMLToDom)(
        "<b>Security warning!</b><br />This will be stored unencrypted in your obsidian plugin folder. Do not use this plugin if you do not fully understand the security implications of this."
      )
    ).addText(
      (text) => text.setPlaceholder("Enter your secret").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

/* nosourcemap */